version: 2
updates:
- package-ecosystem: npm
  directory: /
  schedule:
    interval: weekly
    day: monday
    time: 09:00
    timezone: Asia/Kolkata
  open-pull-requests-limit: 5
  groups:
    routine-updates:
      patterns:
      - '*'
      update-types:
      - minor
      - patch
    security-updates:
      applies-to: security-updates
      patterns:
      - '*'
- package-ecosystem: docker
  directory: /
  schedule:
    interval: weekly
    day: monday
    time: 09:00
    timezone: Asia/Kolkata
  open-pull-requests-limit: 5
  groups:
    routine-updates:
      patterns:
      - '*'
      update-types:
      - minor
      - patch
    security-updates:
      applies-to: security-updates
      patterns:
      - '*'
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
    day: monday
    time: 09:00
    timezone: Asia/Kolkata
  open-pull-requests-limit: 5
  groups:
    routine-updates:
      patterns:
      - '*'
      update-types:
      - minor
      - patch
    security-updates:
      applies-to: security-updates
      patterns:
      - '*'
